stages:
  - release

image: docker:19.03.10


services:
  - docker:dind


variables:
  REGISTRY: 157077562636.dkr.ecr.us-east-2.amazonaws.com
  REPOSITORY_URL: 157077562636.dkr.ecr.us-east-2.amazonaws.com/user_interface_repo
  TASK_DEFINITION_NAME: user_interface
  CLUSTER_NAME: wafflert
  SERVICE_NAME: user_interface_service
  REGION: us-east-2
  TASK_EXECUTION_ROLE: arn:aws:iam::157077562636:role/ecs-task-execution-role


before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REGISTRY
  - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"


release:
  stage: release
  script:
    - echo "Building image..."
    - docker build -t $REPOSITORY_URL:latest .
    - echo "Tagging image..."
    - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
    - docker push $REPOSITORY_URL:$IMAGE_TAG
  only:
    - main
