export const USER_ONBOARDING_STATUS_REQUEST = "USER_ONBOARDING_STATUS_REQUEST";
export const USER_ONBOARDING_STATUS_SUCCESS = "USER_ONBOARDING_STATUS_SUCCESS";
export const USER_ONBOARDING_STATUS_ERROR = "USER_ONBOARDING_STATUS_ERROR";
export const USER_ONBOARDING_STATUS_RESET= "USER_ONBOARDING_STATUS_RESET";

export const CLIENT_SECRET_REQUEST = "CLIENT_SECRET_REQUEST";
export const CLIENT_SECRET_SUCCESS = "CLIENT_SECRET_SUCCESS";
export const CLIENT_SECRET_ERROR = "CLIENT_SECRET_ERROR";
export const CLIENT_SECRET_RESET = "CLIENT_SECRET_RESET";
