export const WAFFLE_RUN_REQUEST = "WAFFLE_RUN_REQUEST";
export const WAFFLE_RUN_SUCCESS = "WAFFLE_RUN_SUCCESS";
export const WAFFLE_RUN_ERROR = "WAFFLE_RUN_ERROR";
export const WAFFLE_RUN_RESET = "WAFFLE_RUN_RESET";

export const WAFFLE_PAST_RUN_REQUEST = "WAFFLE_PAST_RUN_REQUEST";
export const WAFFLE_PAST_RUN_SUCCESS = "WAFFLE_PAST_RUN_SUCCESS";
export const WAFFLE_PAST_RUN_ERROR = "WAFFLE_PAST_RUN_ERROR";
export const WAFFLE_PAST_RUN_RESET = "WAFFLE_PAST_RUN_RESET";

export const WAFFLE_ORDER_REQUEST = "WAFFLE_ORDER_REQUEST";
export const WAFFLE_ORDER_SUCCESS = "WAFFLE_ORDER_SUCCESS";
export const WAFFLE_ORDER_ERROR = "WAFFLE_ORDER_ERROR";
export const WAFFLE_ORDER_RESET = "WAFFLE_ORDER_RESET";

export const WAFFLE_PAST_ORDER_REQUEST = "WAFFLE_PAST_ORDER_REQUEST";
export const WAFFLE_PAST_ORDER_SUCCESS = "WAFFLE_PAST_ORDER_SUCCESS";
export const WAFFLE_PAST_ORDER_ERROR = "WAFFLE_PAST_ORDER_ERROR";
export const WAFFLE_PAST_ORDER_RESET = "WAFFLE_PAST_ORDER_RESET";

export const WAFFLE_CONFIRMED_REQUEST = "WAFFLE_CONFIRMED_REQUEST";
export const WAFFLE_CONFIRMED_SUCCESS = "WAFFLE_CONFIRMED_SUCCESS";
export const WAFFLE_CONFIRMED_ERROR = "WAFFLE_CONFIRMED_ERROR";
export const WAFFLE_CONFIRMED_RESET = "WAFFLE_CONFIRMED_RESET";
