export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_ERROR = "ALL_ORDERS_ERROR";
export const ALL_ORDERS_RESET = "ALL_ORDERS_RESET";