export const USER_ORDER_REQUEST = "USER_ORDER_REQUEST";
export const USER_ORDER_SUCCESS = "USER_ORDER_SUCCESS";
export const USER_ORDER_ERROR = "USER_ORDER_ERROR";
export const USER_ORDER_RESET = "USER_ORDER_RESET";

export const RUNNER_ACCEPT_REQUEST = "RUNNER_ACCEPT_REQUEST";
export const RUNNER_ACCEPT_SUCCESS = "RUNNER_ACCEPT_SUCCESS";
export const RUNNER_ACCEPT_ERROR = "RUNNER_ACCEPT_ERROR";
export const RUNNER_ACCEPT_RESET = "RUNNER_ACCEPT_RESET";


