FROM python:3.9
WORKDIR /usr/src/app
COPY ci/requirements.txt ./
COPY ci/run.sh ./
COPY ./src ./src
COPY tests/*.py ./tests/
RUN chmod 777 -R /usr/src/app && chmod o+t -R /usr/src/app
RUN chmod +x run.sh
RUN pip install --no-cache-dir -r requirements.txt
CMD ./run.sh
