FROM node:14

WORKDIR /usr/src/app

COPY ci ./ci
COPY src ./src
COPY tests ./tests
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install
RUN chmod +x ci/wait-for-it.sh
CMD ci/wait-for-it.sh mysql:3306 -- npm test