stages:
  - release
  - deploy

image: docker:19.03.10


services:
  - docker:dind


variables:
  ECR_ADDRESS: 157077562636.dkr.ecr.us-east-2.amazonaws.com
  REPO_NAME: users_repo
  TASK_DEFINITION_NAME: users
  CLUSTER_NAME: wafflert
  SERVICE_NAME: users_service
  TASK_EXECUTION_ROLE: arn:aws:iam::157077562636:role/ecs-task-execution-role


before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_ADDRESS
  - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"


release:
  stage: release
  script:
    - echo "Building image..."
    - docker build -t $ECR_ADDRESS/$REPO_NAME:latest .
    - echo "Tagging image..."
    - docker tag $ECR_ADDRESS/$REPO_NAME:latest $ECR_ADDRESS/$REPO_NAME:$IMAGE_TAG
    - echo "Pushing image..."
    - docker push $ECR_ADDRESS/$REPO_NAME:latest
    - docker push $ECR_ADDRESS/$REPO_NAME:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo $ECR_ADDRESS/$REPO_NAME:$IMAGE_TAG
    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${AWS_DEFAULT_REGION}")
    - NEW_CONTAINER_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$ECR_ADDRESS/$REPO_NAME:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image = $IMAGE | .taskDefinition.containerDefinitions[0]')
    - echo "Registering new container definition..."
    - aws ecs register-task-definition --region "${AWS_DEFAULT_REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINTIION}" --memory 100 --execution-role-arn "${TASK_EXECUTION_ROLE}"
    - echo "Updating the service..."
    - aws ecs update-service --region "${AWS_DEFAULT_REGION}" --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}"  --task-definition "${TASK_DEFINITION_NAME}"
  only:
    - main
